//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftLaunch.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwiftLaunch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 There should be at least one tab page. 的本地化字符串。
        /// </summary>
        internal static string String_CanNotRemoveLastTabPage {
            get {
                return ResourceManager.GetString("String_CanNotRemoveLastTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm to clear this button? 的本地化字符串。
        /// </summary>
        internal static string String_ConfirmToClearButton {
            get {
                return ResourceManager.GetString("String_ConfirmToClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm to remove this tab page? All the buttons in it shall be lost. 的本地化字符串。
        /// </summary>
        internal static string String_ConfirmToRemoveTabPage {
            get {
                return ResourceManager.GetString("String_ConfirmToRemoveTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index is beyond range. 的本地化字符串。
        /// </summary>
        internal static string String_IndexBeyondRange {
            get {
                return ResourceManager.GetString("String_IndexBeyondRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Button 的本地化字符串。
        /// </summary>
        internal static string String_MoveButton {
            get {
                return ResourceManager.GetString("String_MoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Button Here 的本地化字符串。
        /// </summary>
        internal static string String_MoveButtonHere {
            get {
                return ResourceManager.GetString("String_MoveButtonHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Tab 的本地化字符串。
        /// </summary>
        internal static string String_MoveTab {
            get {
                return ResourceManager.GetString("String_MoveTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Tab Here 的本地化字符串。
        /// </summary>
        internal static string String_MoveTabHere {
            get {
                return ResourceManager.GetString("String_MoveTabHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select target type first. 的本地化字符串。
        /// </summary>
        internal static string String_SelectTargetTypeFirst {
            get {
                return ResourceManager.GetString("String_SelectTargetTypeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tab name can not be empty. 的本地化字符串。
        /// </summary>
        internal static string String_TabNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("String_TabNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target not exist. 的本地化字符串。
        /// </summary>
        internal static string String_TargetNotExist {
            get {
                return ResourceManager.GetString("String_TargetNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One file each time. 的本地化字符串。
        /// </summary>
        internal static string String_TooManyFilesOnce {
            get {
                return ResourceManager.GetString("String_TooManyFilesOnce", resourceCulture);
            }
        }
    }
}
